Feature branch
Adewunmi97/Newsweek-clone pull request #4
Opened 2020-08-27 15:39 UTC by Adewunmi97

- The project involves the use of  HTML, CSS, and bootstrap.
-Added webhint and stylehint.

2020-08-27 16:35 UTC, Adewunmi97 commented
-All webhint errors fixed

2020-08-27 17:08 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello @Adewunmi97 and @oracleot :wave: 

### Your page is looking so good, it's almost identical to the original, I can hardly notice the differences. We only have some little details to fix:

## Page

### Navigation bar

***Medium Screen***

- [x] Your logo should be smaller, just like the original, check below:

**YOURS:**

![Screenshot from 2020-08-27 13-43-45](https://user-images.githubusercontent.com/59691171/91470839-98beb080-e86b-11ea-9bfb-af05cd70ca13.png)
<br>
**ORIGINAL:**

![Screenshot from 2020-08-27 13-43-48](https://user-images.githubusercontent.com/59691171/91470858-a07e5500-e86b-11ea-8425-0f87924ca61f.png)
<br>

### Main Content

***Medium Screen***

- [x] Your 'Free Signup Section' width is too big compared to the original, check below:

**YOURS:**

![Screenshot from 2020-08-27 13-48-05](https://user-images.githubusercontent.com/59691171/91471261-331ef400-e86c-11ea-9b58-a84fc521bd13.png)
<br>

**ORIGINAL:**

![Screenshot from 2020-08-27 13-48-08](https://user-images.githubusercontent.com/59691171/91471284-3c0fc580-e86c-11ea-9e7c-f63f72551080.png)
<br>

***Small Screen***

- [x] I can't see the title of the first section, you need to add some margin, look below:

![Screenshot from 2020-08-27 13-53-01](https://user-images.githubusercontent.com/59691171/91471683-c821ed00-e86c-11ea-963d-990872e58270.png)

<br>

- [x] I can't find the 'More Stories' section in your page, check the original:

![Screenshot from 2020-08-27 13-57-40](https://user-images.githubusercontent.com/59691171/91472188-7b8ae180-e86d-11ea-96f1-14a42c9bb306.png)

<br>

- [x] Now here's something that most students miss: **'The Famous Newsletter Section'**, the image vanishes on small screens :fearful:  Check below:

**YOURS:**

![Screenshot from 2020-08-27 14-00-50](https://user-images.githubusercontent.com/59691171/91472623-200d2380-e86e-11ea-8deb-b43a24ba2cd7.png)
<br>
**ORIGINAL:**

![Screenshot from 2020-08-27 14-00-54](https://user-images.githubusercontent.com/59691171/91472641-26030480-e86e-11ea-83e6-2d3cbcb8e7a7.png)
<br>

## General

- [ ] Just check my single comment in your code below :wink: 

## Summary

- Your code is beautiful, everything is in its place, all good HTML and CSS practices :+1: 
- You mastered the use of Bootstrap, it's really awesome, congratulations :clap: :clap:
- Great repository, very professional, keep up the good work :rocket:  
- We still need to fix some details about the layout, but most of it is in place :smile: 

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-27 17:08 UTC, MuriloRoque commented on styles.css
> +  /* background-color: rgba(0,0,0,0.1); */
Please, remove this commented code, I think you missed it :wink:

2020-08-28 15:56 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:

### General requirements 
- [ ] Remove `.vscode` directory or add to .gitginore file
- [ ] Reove extra padding in the page
![image](https://user-images.githubusercontent.com/24902525/91587255-1fcb6180-e91c-11ea-809c-465cbad87294.png)


### Specific req.

| Section/Screen                             | Large | Medium | Small |
| :----------------------------------------- | :---: | :----: | :---: |
| Navbar              |      |      |       |
| Featured stories              |      |        |       |
| Top story             |       |        |       |
| My turn             |       |        |   1    |
| Cultural&Travel             |      |        |    1   |
| Opinion                 |       |        |       |
| Latest news                  |       |        |       |
| More stories |      |        |       |
| In the magazine         |       |        |       |
| Editor's pick |    |     |      |
| Footer                                     |       |        |       |
###### This table is given each section with his screen width approach, each issue is given by number below this table

1.  After more stories section you're missing to add my turn and culture& travel sections
![image](https://user-images.githubusercontent.com/24902525/91587804-e47d6280-e91c-11ea-9689-a4c42f433745.png)

### Summary

-  Remove extra padding entire page
- You're missing two sections for small screens 

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-28 18:59 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-28 19:31 UTC, merged